//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBoto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidate()
        {
            this.Winners = new HashSet<Winner>();
        }
    
        public int CandidateId { get; set; }
        public string CandidateName { get; set; }
        public string Partylist { get; set; }
        public int PositionId { get; set; }
        public string Motto { get; set; }
        public string Image { get; set; }
        public int DepartmentId { get; set; }
        public int ElectionId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Election Election { get; set; }
        public virtual Position Position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Winner> Winners { get; set; }
    }
}
