//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBoto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        public int CandidateId { get; set; }
        public string CandidateName { get; set; }
        public string Partylist { get; set; }
        public int PositionId { get; set; }
        public string Motto { get; set; }
        public string Image { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> ElectionId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Election Election { get; set; }
        public virtual Position Position { get; set; }
    }
}
