//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBoto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Election
    {
        public int ElectionId { get; set; }
        public string ElectionName { get; set; }
        public string Department { get; set; }
        public string Description { get; set; }
        public bool Status { get; set; }
        public int DepartmentId { get; set; }
    
        public virtual Department Department1 { get; set; }
    }
}
