//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBoto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voter
    {
        public int VoterId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string ContactNumber { get; set; }
        public string Email { get; set; }
        public string Province { get; set; }
        public string Barangay { get; set; }
        public string City { get; set; }
        public string Year { get; set; }
        public string Section { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public bool Status { get; set; }
        public int DepartmentId { get; set; }
        public int VotedCandidatesId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual VotedCandidate VotedCandidate { get; set; }
    }
}
